resource_type: ExternalIPPool
event: Delete
phase: main
priority: 100
failure_policy: Fail

parameters:
  - name: external_ip_pool
    type: dict
    required: true
    description: ExternalIPPool Kubernetes resource

outputs: []
