resource_type: PublicIPAttachment
event: Delete
phase: main
priority: 100
failure_policy: Fail

parameters:
  - name: public_ip
    type: dict
    required: true
    description: >-
      PublicIP Kubernetes resource with annotations
      osac.openshift.io/publicippool-name and
      osac.openshift.io/publicip-target-namespace

outputs: []
